-- Institution lists, exactly as PORTAL_SPEC.md §7.1. The owner edits them in Settings.
-- Recording only: MFG never recommends any institution.
insert into public.institutions (debt_type, name, sort) values
  ('Credit card', 'Absa', 0),
  ('Credit card', 'African Bank', 1),
  ('Credit card', 'Capitec', 2),
  ('Credit card', 'Discovery Bank', 3),
  ('Credit card', 'FNB', 4),
  ('Credit card', 'Investec', 5),
  ('Credit card', 'Nedbank', 6),
  ('Credit card', 'Standard Bank', 7),
  ('Credit card', 'Woolworths', 8),
  ('Credit card', 'RCS', 9),
  ('Store account', 'Edgars', 0),
  ('Store account', 'Truworths', 1),
  ('Store account', 'Identity', 2),
  ('Store account', 'TFG (Foschini, Markham, Sportscene, Totalsports)', 3),
  ('Store account', 'Mr Price', 4),
  ('Store account', 'Woolworths', 5),
  ('Store account', 'Ackermans', 6),
  ('Store account', 'Lewis', 7),
  ('Store account', 'Beares', 8),
  ('Store account', 'Best Home and Electric', 9),
  ('Store account', 'RCS', 10),
  ('Personal loan', 'Absa', 0),
  ('Personal loan', 'African Bank', 1),
  ('Personal loan', 'Capitec', 2),
  ('Personal loan', 'FNB', 3),
  ('Personal loan', 'Nedbank', 4),
  ('Personal loan', 'Standard Bank', 5),
  ('Personal loan', 'DirectAxis', 6),
  ('Personal loan', 'FinChoice', 7),
  ('Personal loan', 'Sanlam', 8),
  ('Personal loan', 'Old Mutual Finance', 9),
  ('Personal loan', 'Bayport', 10),
  ('Personal loan', 'RCS', 11),
  ('Personal loan', 'WesBank', 12),
  ('Personal loan', 'Wonga', 13),
  ('Micro / short-term loan', 'Wonga', 0),
  ('Micro / short-term loan', 'FinChoice', 1),
  ('Micro / short-term loan', 'Finbond', 2),
  ('Micro / short-term loan', 'African Bank', 3),
  ('Micro / short-term loan', 'Capitec', 4),
  ('Vehicle finance', 'WesBank', 0),
  ('Vehicle finance', 'Absa Vehicle and Asset Finance', 1),
  ('Vehicle finance', 'Standard Bank Vehicle and Asset Finance', 2),
  ('Vehicle finance', 'MFC (Nedbank)', 3),
  ('Vehicle finance', 'Toyota Financial Services', 4),
  ('Vehicle finance', 'BMW Financial Services', 5),
  ('Vehicle finance', 'Mercedes-Benz Financial Services', 6),
  ('Home loan', 'Absa', 0),
  ('Home loan', 'FNB', 1),
  ('Home loan', 'Nedbank', 2),
  ('Home loan', 'Standard Bank', 3),
  ('Home loan', 'Investec', 4),
  ('Home loan', 'SA Home Loans', 5),
  ('Overdraft', 'Absa', 0),
  ('Overdraft', 'African Bank', 1),
  ('Overdraft', 'Capitec', 2),
  ('Overdraft', 'Discovery Bank', 3),
  ('Overdraft', 'FNB', 4),
  ('Overdraft', 'Investec', 5),
  ('Overdraft', 'Nedbank', 6),
  ('Overdraft', 'Standard Bank', 7),
  ('Overdraft', 'TymeBank', 8),
  ('Overdraft', 'Old Mutual', 9),
  ('Overdraft', 'Bidvest Bank', 10),
  ('Overdraft', 'Access Bank', 11),
  ('Overdraft', 'Bank Zero', 12),
  ('Overdraft', 'Ubank', 13),
  ('Overdraft', 'GBS Mutual Bank', 14),
  ('Overdraft', 'Finbond', 15),
  ('Pay later', 'Payflex', 0),
  ('Pay later', 'PayJustNow', 1),
  ('Pay later', 'MoreTyme (TymeBank)', 2),
  ('Pay later', 'Happy Pay', 3),
  ('Pay later', 'Float', 4),
  ('Pay later', 'Mobicred', 5),
  ('Cellphone contract', 'Vodacom', 0),
  ('Cellphone contract', 'MTN', 1),
  ('Cellphone contract', 'Telkom', 2),
  ('Cellphone contract', 'Cell C', 3),
  ('Cellphone contract', 'Rain', 4)
on conflict (debt_type, name) do nothing;
